routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('admin')->middleware('role:superadministrator|administrator|editor|author|contributor')->group(function () {
  Route::get('/', 'AdminController@index')->name('admin');
  Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
  Route::resource('/users', 'UserController');
  Route::resource('/permissions', 'PermissionController');
  Route::resource('/roles', 'RoleController');
  Route::resource('/posts', 'PostController');
});

Route::get('/home', 'HomeController@index')->name('home');

app/Role.php
<?php

namespace App;

use Laratrust\LaratrustRole;

class Role extends LaratrustRole
{
    public function checked($allPerms)
    {
        if($this->Permissions()->get()->count()){
            $data = '';
            foreach ($this->Permissions()->get() as $permission) {
                if($permission->id == $allPerms) $data = 'checked';
            }
            return $data;
        }
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;
use App\Permission;
use Session;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $roles = Role::all();
      return view('admin.roles.index')->withRoles($roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $permissions = Permission::all();
      return view('admin.roles.create')->withPermissions($permissions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validateWith([
        'display_name' => 'required|max:255',
        'name' => 'required|max:100|alpha_dash|unique:roles',
        'description' => 'sometimes|max:255'
      ]);

      $role = new Role();
      $role->display_name = $request->display_name;
      $role->name = $request->name;
      $role->description = $request->description;
      $role->save();

      if ($request->permissions) {
        $role->syncPermissions($request->permissions);
      }

      Session::flash('success', 'Successfully created the new '. $role->display_name . ' role in the database.');
      return redirect()->route('roles.show', $role->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $role = Role::where('id', $id)->with('permissions')->first();
      return view('admin.roles.show')->withRole($role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $role = Role::where('id', $id)->with('permissions')->first();
      $permissions = Permission::all();
      return view('admin.roles.edit')->withRole($role)->withPermissions($permissions);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validateWith([
        'display_name' => 'required|max:255',
        'description' => 'sometimes|max:255'
      ]); 

      $role = Role::findOrFail($id);
      $role->display_name = $request->display_name;
      $role->description = $request->description;
      $role->save();

      if ($request->permissions) {
        $role->syncPermissions($request->permissions);
      }

      Session::flash('success', 'Successfully update the '. $role->display_name . ' role in the database.');
      return redirect()->route('roles.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);    
        $role->forceDelete();
        Session::flash('warning','The Role deleted successfully');
        return redirect()->back();
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin')
@section('title','Add Role')

@section('content')
@section('breadcrumb')
  <li>Role</li>
  <li class="active">Add</li>
@endsection
@include ('admin.parts.errors')
<form role="form" action="{{route('roles.store')}}" method="POST">
{{csrf_field()}}
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h3 class="title">Add a Role</h3>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
        <div class="btn-lh">
           <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> Create New Role</button>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <div class="form-group">
        <label>Name (Human Readable)</label>
        <input class="form-control" placeholder="Name" name="display_name" id="name" value="{{old('display_name')}}">
      </div>

      <div class="form-group">
        <label>Slug</label>
        <input class="form-control" placeholder="Slug" name="name"  value="{{old('name')}}" id="name">
      </div>
      <div class="form-group">
        <label>Description</label>
        <textarea rows="3" class="form-control"  id="description" name="description">{{old('description')}}</textarea>
      </div>

      

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Roles:</label>
        @foreach ($permissions as $permission)
          <div class="checkbox">
            <label>
              <input type="checkbox" name="permissions[]" value="{{$permission->id}}">{{$permission->display_name}}
            </label>
          </div>
        @endforeach
      </div>
    </div>
  </div>
</div>
</form>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin')
@section('title','Edit Role')

@section('content')
@section('breadcrumb')
  <li>Role</li>
  <li class="active">Edit</li>
@endsection
@include ('admin.parts.errors')
<form role="form" action="{{route('roles.update', $role->id)}}" method="POST">
{{method_field('PUT')}}
{{csrf_field()}}
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h3 class="title">Edit Role</h3>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
        <div class="btn-lh">
           <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update</button>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <div class="form-group">
        <label>Name (Human Readable)</label>
        <input class="form-control" placeholder="Name" name="display_name" id="name" value="{{$role->display_name}}">
      </div>

      <div class="form-group">
        <label>Slug (Can not be edited)</label>
        <input class="form-control" placeholder="email" name="name"  value="{{$role->name}}" disabled id="name">
      </div>
      <div class="form-group">
        <label>Description</label>
        <textarea rows="3" class="form-control"  id="description" name="description">{{$role->description}}</textarea>
      </div>

      

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Roles:</label>
        @foreach ($permissions as $permission)
          <div class="checkbox">
            <label>
              <input type="checkbox" name="permissions[]" {{$role->checked($permission->id)}} value="{{$permission->id}}">{{$permission->display_name}}
            </label>
          </div>
        @endforeach
      </div>
    </div>
  </div>
</div>
</form>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')
@section('title','Roles')

@section('content')
@section('breadcrumb')
  <li class="active">Roles</li>
@endsection
<div class="panel  panel-default">
  <div class="panel-heading">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <h3 class="title">Manage Roles</h3>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
      <div class="btn-lh"><a href="{{route('roles.create')}}" class="btn btn-primary "><i class="fa fa-user-plus"></i> Create New Role</a></div>
    </div>
  </div>
</div>
<div class="panel-body">
  <div class="row">
    @foreach ($roles as $role)
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <div class="box">
          <article class="panel panel-default" style='border:1px solid #ddd'>
              <div class="panel-body">
              <div class="content">
                <h3 class="title">{{$role->display_name}}</h3>
                <h4 class="subtitle"><em>{{$role->name}}</em></h4>
                <p>
                  {{$role->description}}
                </p>
              </div>

              <div class="buttons">
                <div class="dsinb">
                  <a href="{{route('roles.show', $role->id)}}" class="btn btn-primary"><i class="fa fa-info"></i> Details</a>
                </div>
                <div class="dsinb">
                  <a href="{{route('roles.edit', $role->id)}}" class="btn btn-success"><i class="fa fa-edit"></i> Edit</a>
                </div>
                <form class="dsinb" method="POST" action="{{route('roles.destroy', $role->id)}}">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button class=" btn btn-danger"><i class="fa fa-close"></i> Delete</button>
                </form>
              </div>
            </div>
          </article>
        </div>
      </div>
    @endforeach
  </div>
  </div>
  </div>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.admin')
@section('title','Role Detail')

@section('content')
@section('breadcrumb')
  <li>Role</li>
  <li class="active">Detail</li>
@endsection

<div class="panel panel-default">
<div class="panel-heading">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <h3 class="title">Role Info</h3>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
          <div class="btn-lh">
            <a href="{{route('roles.edit', $role->id)}}" class="btn-success btn"><i class="fa fa-edit "></i> Edit Role</a>
          </div>
        </div>
      </div>
</div>

<div class="panel-body">
  <form action="" method="post">
    <fieldset>
      <!-- Name input-->
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <div class="form-group">
          <h3 class="title">{{$role->display_name}} <small class="m-l-25"><em>({{$role->name}})</em></small></h3>
          <h5>{{$role->description}}</h5>
      </div>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      
      <!-- Message body -->
      <div class="form-group">
        <label class="col-md-3 control-label" for="message">Role Permissions</label>
        <div class="col-md-9">
            <ul>
              @foreach ($role->permissions as $r)
                <li>{{$r->display_name}} <em class="m-l-15">({{$r->description}})</em></li>
              @endforeach
            </ul>
        </div>
      </div>
    </div>
    </fieldset>
  </form>
</div>
</div>
@endsection



@section('content')
  <div class="flex-container">
    <div class="columns m-t-10">
      <div class="column">
        <h1 class="title">{{$role->display_name}}<small class="m-l-25"><em>({{$role->name}})</em></small></h1>
        <h5>{{$role->description}}</h5>
      </div>
      <div class="column">
        <a href="{{route('roles.edit', $role->id)}}" class="button is-primary is-pulled-right"><i class="fa fa-user-plus m-r-10"></i> Edit this Role</a>
      </div>
    </div>
    <hr class="m-t-0">

    <div class="columns">
      <div class="column">
        <div class="box">
          <article class="media">
            <div class="media-content">
              <div class="content">
                <h2 class="title">Permissions:</h1>
                <ul>
                  @foreach ($role->permissions as $r)
                    <li>{{$r->display_name}} <em class="m-l-15">({{$r->description}})</em></li>
                  @endforeach
                </ul>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
@endsection