routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('admin')->middleware('role:superadministrator|administrator|editor|author|contributor')->group(function () {
  Route::get('/', 'AdminController@index')->name('admin');
  Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
  Route::resource('/users', 'UserController');
  Route::resource('/permissions', 'PermissionController');
  Route::resource('/roles', 'RoleController');
  Route::resource('/posts', 'PostController');
});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/parts/errors.blade.php
@if(count($errors))
<div class="form-group">
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<ul>
		@foreach ($errors->all()  as $error)
		<li>
			{{ $error }}
		</li>
		@endforeach
	</ul>
</div>	
</div>
@endif

resources/views/admin/parts/navbar.blade.php
<div class="container-fluid">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span></button>
		<a class="navbar-brand" href="#"><span>CMS</span>Panel</a>
		<ul class="nav navbar-top-links navbar-right">
			<li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
				<em class="fa fa-bell"></em><span class="label label-info">5</span>
			</a>
				<ul class="dropdown-menu dropdown-alerts">
					<li><a href="#">
						<div><em class="fa fa-envelope"></em> 1 New Message
							<span class="pull-right text-muted small">3 mins ago</span></div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
						<div><em class="fa fa-heart"></em> 12 New Likes
							<span class="pull-right text-muted small">4 mins ago</span></div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
						<div><em class="fa fa-user"></em> 5 New Followers
							<span class="pull-right text-muted small">4 mins ago</span></div>
					</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div><!-- /.container-fluid -->

resources/views/admin/parts/sidebar.blade.php
	<div class="profile-sidebar">
		<div class="profile-userpic">
			<img src="{{ Auth::user()->getAvatar(50) }}" class="img-responsive" alt="">
		</div>
		<div class="profile-usertitle">
			<div class="profile-usertitle-name">{{ Auth::user()->name }}</div>
			<div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="divider"></div>
	<form role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Search">
		</div>
	</form>
	<ul class="nav menu">
		{{-- <li class="{{ Request::path() == 'admin/dashboard' ? 'active' : '' }}">
			<a href="{{ route('admin.dashboard') }}"><em class="fa fa-dashboard">&nbsp;</em> ده‌ستپێك</a>
		</li> --}}
		<li class="{{ Request::path() == 'admin/dashboard' ? 'active' : '' }}">
			<a href="{{ route('admin.dashboard') }}"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a>
		</li>

		<li <li class="{{ (Request::path() == 'admin/users' || Request::path() == 'admin/roles' || Request::path() == 'admin/permissions' ) ? 'active' : '' }} parent"><a data-toggle="collapse" href="{{route('users.index')}}" class="{{Nav::isResource('users')}}">
			<em class="fa fa-users">&nbsp;</em> User Settings <span data-toggle="collapse" href="#sub-item-1" class="icon pull-right"><em class="fa fa-plus"></em></span>
			{{-- <em class="fa fa-users">&nbsp;</em> ڕێكخستنی به‌كارهێنه‌ران <span data-toggle="collapse" href="#sub-item-1" class="icon pull-left"><em class="fa fa-plus"></em></span> --}}
			</a>
			<ul class="children collapse" id="sub-item-1">
				<li><a href="{{route('users.index')}}" class="{{Nav::isResource('users')}}"><span class="fa fa-user">&nbsp;</span>  به‌كارهێنه‌ران</a></li>
				<li><a href="{{route('roles.index')}}" class="{{Nav::isResource('roles')}}"><span class="fa fa-cog">&nbsp;</span> پله‌كان</a></li>
				<li><a href="{{route('permissions.index')}}" class="{{Nav::isResource('permissions')}}"><span class="fa fa-hourglass">&nbsp;</span> ده‌سه‌ڵاته‌كان</a></li>
			</ul>
		</li>
		<li>
        <a href="{{ route('logout') }}"
            onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
           <em class="fa fa-power-off">&nbsp;</em> Logout
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
	 </li>
	</ul>
</div><!--/.sidebar-->