routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('admin')->middleware('role:superadministrator|administrator|editor|author|contributor')->group(function () {
  Route::get('/', 'AdminController@index')->name('admin');
  Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
  Route::resource('/users', 'UserController');
  Route::resource('/permissions', 'PermissionController');
  Route::resource('/roles', 'RoleController');
  Route::resource('/posts', 'PostController');
});

Route::get('/home', 'HomeController@index')->name('home');

app/Permission.php
<?php

namespace App;

use Laratrust\LaratrustPermission;

class Permission extends LaratrustPermission
{
    //
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;
use Session;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $permissions = Permission::all();
      return view('admin.permissions.index')->withPermissions($permissions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validateWith([
          'display_name' => 'required|max:255',
          'name' => 'required|max:255|alphadash|unique:permissions,name',
          'description' => 'sometimes|max:255'
        ]);

        $permission = new Permission();
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();

        Session::flash('success', 'Permission has been successfully added');
        return redirect()->route('permissions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $permission = Permission::findOrFail($id);
      return view('admin.permissions.show')->withPermission($permission);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $permission = Permission::findOrFail($id);
      return view('admin.permissions.edit')->withPermission($permission);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validateWith([
        'display_name' => 'required|max:255',
        'description' => 'sometimes|max:255'
      ]);
      $permission = Permission::findOrFail($id);
      $permission->display_name = $request->display_name;
      $permission->description = $request->description;
      $permission->save();

      Session::flash('success', 'Updated the '. $permission->display_name . ' permission.');
      return redirect()->route('permissions.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::find($id);    
        $permission->forceDelete();
        Session::flash('warning','The Permission deleted successfully');
        return redirect()->back();
    }
}

resources/views/admin/permissions/create.blade.php
@extends('layouts.admin')
@section('title','Add Permission')

@section('content')
@section('breadcrumb')
  <li>Permissions</li>
  <li class="active">Add</li>
@endsection
@include ('admin.parts.errors')
<form role="form" action="{{route('permissions.store')}}" method="POST">
{{csrf_field()}}
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h3 class="title">Add a Permission</h3>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
        <div class="btn-lh">
           <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> Create New Permission</button>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <div class="form-group">
        <label>Name (Human Readable)</label>
        <input class="form-control" placeholder="Name" name="display_name" id="name" value="{{old('display_name')}}">
      </div>

      <div class="form-group">
        <label>Slug </label>
        <input class="form-control" placeholder="Slug" name="name"  value="{{old('name')}}" id="name">
      </div>

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Description</label>
        <textarea rows="6" class="form-control"  id="description" name="description">{{old('description')}}</textarea>
      </div>
    </div>
  </div>
</div>
</form>
@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts.admin')
@section('title','Edit Permission')

@section('content')
@section('breadcrumb')
  <li>Permission</li>
  <li class="active">Edit</li>
@endsection
@include ('admin.parts.errors')
<form role="form" action="{{route('permissions.update', $permission->id)}}" method="POST">
{{method_field('PUT')}}
{{csrf_field()}}
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h3 class="title">Edit Permission</h3>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
        <div class="btn-lh">
           <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update</button>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-md-6">
      <div class="form-group">
        <label>Name (Display Name)</label>
        <input class="form-control" placeholder="Name" name="display_name" id="display_name" value="{{$permission->display_name}}">
      </div>

      <div class="form-group">
        <label>Slug <small>(Cannot be changed)</small></label>
        <input class="form-control"  name="name" id="name" value="{{$permission->name}}" disabled>
      </div>


    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Description</label>
        <textarea rows="6" class="form-control"  id="description" name="description">{{$permission->description}}</textarea>
      </div>
    </div>
  </div>
</div>
</form>
@endsection

resources/views/admin/permissions/index.blade.php
@extends('layouts.admin')
@section('title','Permissions')

@section('content')
  @section('breadcrumb')
    <li>User</li>
    <li class="active">Permissions</li>
  @endsection
    
<div class="panel panel-default articles">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <h1 class="title">Manage Permissions</h1>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
          <div class="btn-lh">
            <a href="{{route('permissions.create')}}" class="btn-primary btn"><i class="fa fa-user-plus m-r-10"></i> Create New Permission</a>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="table-hl">
        <table class="table table-hover ">
          <thead>
            <tr>
              <th>Name</th>
              <th>Slug</th>
              <th>Description</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            @foreach ($permissions as $permission)
              <tr>
                <th>{{$permission->display_name}}</th>
                <td>{{$permission->name}}</td>
                <td>{{$permission->description}}</td>
                
                <td class="text-left">
                  <a class='btn btn-info btn-xs' href="{{route('permissions.show', $permission->id)}}" ><i class="fa fa-eye"></i> View</a>
                  <a class="btn btn-success btn-xs" href="{{route('permissions.edit', $permission->id)}}"><i class="fa fa-edit"></i> Edit</a>
                  <form class="dsinb" method="POST" action="{{route('permissions.destroy', $permission->id)}}">
                      <input type="hidden" name="_method" value="DELETE">
                      <input type="hidden" name="_token" value="{{ csrf_token() }}">
                      <button class=" btn btn-danger btn-xs"><i class="fa fa-close"></i> Delete</button>
                  </form>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
</div>
@endsection

resources/views/admin/permissions/show.blade.php
@extends('layouts.admin')
@section('title','Permission Detail')

@section('content')
@section('breadcrumb')
  <li>Permission</li>
  <li class="active">Detail</li>
@endsection

<div class="panel panel-default">
<div class="panel-heading">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <h3 class="title">Permission Detail</h3>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" >
          <div class="btn-lh">
            <a href="{{route('permissions.edit', $permission->id)}}" class="btn-success btn"><i class="fa fa-edit "></i> Edit Permission</a>
          </div>
        </div>
      </div>
</div>

<div class="panel-body">
  <form action="" method="post">
    <fieldset>
      <!-- Name input-->
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <div class="form-group">
          <h3 class="title">{{$permission->display_name}} <small class="m-l-25"><em>({{$permission->name}})</em></small></h3>
          <h5>{{$permission->description}}</h5>
      </div>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      
      <!-- Message body -->
      
    </div>
    </fieldset>
  </form>
</div>
</div>
@endsection